apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: micro-service-demo
build:
  artifacts:
    - image: micro-demo-user1
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
    - infra/k8s/user-k8s.yaml
