apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-demo-admin-deploayment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-demo-admin-deploayment
  template:
    metadata:
      labels:
        app: micro-demo-admin-deploayment
    spec:
      containers:
      - name: micro-demo-admin-deploayment
        imagePullPolicy: IfNotPresent
        image: micro-demo-admin
        env:
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLIENT_ID
            value: '302'
          - name: NATS_CLUSTER_ID
            value: 'micro-demo'
          - name: PORTS
            value: '6000'
          - name: DB_URL
            value: 'mongodb://micro-demo-mongo-service/27017/'
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: micro-demo-admin-service
spec:
  selector:
    app: micro-demo-admin-deploayment
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  # type: LoadBalancer
