apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-demo-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-demo-auth-deployment
  template:
    metadata:
      labels:
        app: micro-demo-auth-deployment
    spec:
      containers:
        - name: micro-demo-auth-deployment
          imagePullPolicy: IfNotPresent
          image: irfan76k/micro-demo-auth
          env:
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: "micro-demo"
            - name: PORT
              value: "8000"
            - name: DB_URL
              value: "mongodb://micro-demo-mongo-service/"
            - name: ADMIN_JWT-ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: micro-demo-secret
                  key: ADMIN_JWT_ACCESS_TOKEN_SECRET
            - name: ADMIN_JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: micro-demo-secret
                  key: ADMIN_JWT_REFRESH_TOKEN_SECRET
            - name: USER_JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: micro-demo-secret
                  key: USER_JWT_ACCESS_TOKEN_SECRET
            - name: USER_JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: micro-demo-secret
                  key: USER_JWT_REFRESH_TOKEN_SECRET
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: micro-demo-auth-service
spec:
  selector:
    app: micro-demo-auth-deployment
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  # type: LoadBalancer
