apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micro-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: test-app.com
      http:
        paths:
          - path: /sample/?(.*)
            pathType: Prefix
            backend:
              service:
                name: micro-demo-nginx-service
                port:
                  number: 80
          - path: /test/?(.*)
            pathType: Prefix
            backend:
              service:
                name: micro-demo-user-service
                port:
                  number: 5000
          # - path: /payment/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: micro-demo-payment-service
          #       port:
          #         number: 7000
