apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-demo-inventory-booking-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-demo-inventory-booking-deployment
  template:
    metadata:
      labels:
        app: micro-demo-inventory-booking-deployment
    spec:
      containers:
      - name: micro-demo-inventory-booking-deployment
        imagePullPolicy: IfNotPresent
        image: irfan76k/micro-demo-inventory-booking
        env:
          - name: NATS_URL
            value: "http://nats-srv:4222"
          - name: NATS_CLIENT_ID
            valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          - name: NATS_CLUSTER_ID
            value: "micro-demo"
          - name: PORT
            value: "8000"
          - name: DB_URL
            value: "mongodb://micro-demo-mongo-service"
          - name: ACCESS_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: micro-demo-secret
                key: ADMIN_JWT_ACCESS_TOKEN_SECRET
          - name: REFRESH_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: micro-demo-secret
                key: ADMIN_JWT_REFRESH_TOKEN_SECRET
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: micro-demo-inventory-booking-service
spec:
  selector:
    app: micro-demo-inventory-booking-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  # type: LoadBalancer
