apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-demo-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-demo-notification
  template:
    metadata:
      labels:
        app: micro-demo-notification
    spec:
      containers:
        - name: micro-demo-notification
          imagePullPolicy: IfNotPresent
          image: irfan76k/micro-demo-notification
          env:
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: "micro-demo"
            - name: PORT
              value: "8000"
            - name: DB_URL
              value: "mongodb://micro-demo-mongo-service/"
            - name: NODEMAILER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: micro-demo-secret
                  key: NODEMAILER_EMAIL
            - name: NODEMAILER_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: micro-demo-secret
                  key: NODEMAILER_EMAIL_PASSWORD
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: micro-demo-auth-service
spec:
  selector:
    app: micro-demo-notification
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8000
  # type: LoadBalancer
