apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-demo-payment-deploayment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-demo-payment-deploayment
  template:
    metadata:
      labels:
        app: micro-demo-payment-deploayment
    spec:
      containers:
      - name: micro-demo-payment-deploayment
        imagePullPolicy: IfNotPresent
        image: micro-demo-payment
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing  
          - name: PORT
            value: '7000'
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: micro-demo-payment-service
spec:
  selector:
    app: micro-demo-payment-deploayment
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: LoadBalancer
